/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ASUS ZENBOOK
 */
public class VDashboard extends javax.swing.JFrame {

    /**
     * Creates new form VDashboard
     */
    public VDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        supplierDetailsBtn = new javax.swing.JButton();
        medicineDetailsBtn = new javax.swing.JButton();
        customerDetailsBtn = new javax.swing.JButton();
        employeeDetailsBtn = new javax.swing.JButton();
        billingDetailsBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        userProfileBtn = new javax.swing.JButton();
        orderDetailsBtn = new javax.swing.JButton();
        salesDetailsBtn = new javax.swing.JButton();
        stockDetailsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logoutBtn.setBackground(new java.awt.Color(0, 153, 102));
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setBorder(null);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setText("Dashboard");

        supplierDetailsBtn.setBackground(new java.awt.Color(102, 204, 0));
        supplierDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        supplierDetailsBtn.setText("Supplier Details");
        supplierDetailsBtn.setBorder(null);
        supplierDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierDetailsBtnActionPerformed(evt);
            }
        });

        medicineDetailsBtn.setBackground(new java.awt.Color(102, 204, 0));
        medicineDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        medicineDetailsBtn.setText("Medicine Details");
        medicineDetailsBtn.setBorder(null);
        medicineDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineDetailsBtnActionPerformed(evt);
            }
        });

        customerDetailsBtn.setBackground(new java.awt.Color(102, 204, 0));
        customerDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerDetailsBtn.setText("Customer Details");
        customerDetailsBtn.setBorder(null);
        customerDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerDetailsBtnActionPerformed(evt);
            }
        });

        employeeDetailsBtn.setBackground(new java.awt.Color(102, 204, 0));
        employeeDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeDetailsBtn.setText("Employee Details");
        employeeDetailsBtn.setBorder(null);
        employeeDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeDetailsBtnActionPerformed(evt);
            }
        });

        billingDetailsBtn.setBackground(new java.awt.Color(102, 204, 0));
        billingDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        billingDetailsBtn.setText("Billing Details");
        billingDetailsBtn.setBorder(null);
        billingDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingDetailsBtnActionPerformed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(0, 153, 102));
        exitBtn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        exitBtn.setText("x");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        userProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProfileBtnActionPerformed(evt);
            }
        });

        orderDetailsBtn.setBackground(new java.awt.Color(102, 204, 0));
        orderDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        orderDetailsBtn.setText("Order Details");
        orderDetailsBtn.setBorder(null);
        orderDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderDetailsBtnActionPerformed(evt);
            }
        });

        salesDetailsBtn.setBackground(new java.awt.Color(102, 204, 0));
        salesDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        salesDetailsBtn.setText("Sales Details");
        salesDetailsBtn.setBorder(null);
        salesDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesDetailsBtnActionPerformed(evt);
            }
        });

        stockDetailsBtn.setBackground(new java.awt.Color(102, 204, 0));
        stockDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stockDetailsBtn.setText("Stock Details");
        stockDetailsBtn.setBorder(null);
        stockDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockDetailsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(368, 368, 368)
                .addComponent(exitBtn)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(medicineDetailsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(stockDetailsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(employeeDetailsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(billingDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)
                        .addComponent(salesDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(userProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(orderDetailsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerDetailsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(supplierDetailsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(medicineDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(stockDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(employeeDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(customerDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(orderDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(supplierDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(userProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(salesDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(billingDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        //Logout Button
        this.dispose();
        VLogin obj = new VLogin();
        obj.show();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void supplierDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierDetailsBtnActionPerformed
        // Supplier Details Button
        VSupplierDetails obj = new VSupplierDetails();
        obj.show();
        // Close the Dashboard
        this.dispose();
    }//GEN-LAST:event_supplierDetailsBtnActionPerformed

    private void medicineDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineDetailsBtnActionPerformed
        // Medicine Details Button
        VMedicineDetails obj = new VMedicineDetails();
        obj.show();
        // Close the Dashboard
        this.dispose();
    }//GEN-LAST:event_medicineDetailsBtnActionPerformed

    private void customerDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerDetailsBtnActionPerformed
        // Customer Details Button
        VCustomerDetails obj = new VCustomerDetails();
        obj.show();
        // Close the Dashboard
        this.dispose();
    }//GEN-LAST:event_customerDetailsBtnActionPerformed

    private void employeeDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDetailsBtnActionPerformed
        // Employee Details Button
        VEmployeeDetails obj = new VEmployeeDetails();
        obj.show();
        // Close the Dashboard
        this.dispose();
    }//GEN-LAST:event_employeeDetailsBtnActionPerformed

    private void billingDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingDetailsBtnActionPerformed
        // Billing Details Button
        VBillingDetails obj = new VBillingDetails();
        obj.show();
        // Close the Dashboard
        this.dispose();
    }//GEN-LAST:event_billingDetailsBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        //Exit Button
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void userProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProfileBtnActionPerformed
        // User Profile Button
        VUserProfile obj = new VUserProfile();
        obj.show();
    }//GEN-LAST:event_userProfileBtnActionPerformed

    private void orderDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderDetailsBtnActionPerformed
        // Order Details Button
        VOrderDetails obj = new VOrderDetails();
        obj.show();
        // Close the Dashboard
        this.dispose();
    }//GEN-LAST:event_orderDetailsBtnActionPerformed

    private void salesDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesDetailsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salesDetailsBtnActionPerformed

    private void stockDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockDetailsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockDetailsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billingDetailsBtn;
    private javax.swing.JButton customerDetailsBtn;
    private javax.swing.JButton employeeDetailsBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton medicineDetailsBtn;
    private javax.swing.JButton orderDetailsBtn;
    private javax.swing.JButton salesDetailsBtn;
    private javax.swing.JButton stockDetailsBtn;
    private javax.swing.JButton supplierDetailsBtn;
    private javax.swing.JButton userProfileBtn;
    // End of variables declaration//GEN-END:variables
}
